### ISSUE TITLE
Kangerlussuaq glacier in SE produces unrealistic values 

### ISSUE THREAD

**Issue by signehl** [GEUS-Glaciology-and-Climate/ice_discharge#36]
After updating Sentinel1 IV in June, output from Kangerlussuaq glacier is low. The gate is now too close to the margin and needs to be moved inland.

**Comment by signehl** [comment]
Similar issue occurred in 2021 with the gate of at Sermeq Kujalleq/Jakobshavn Isbræ i 2021 (issue #24). A similar approach to #24 is used here to move the gate inland. 
The old gate in red and the new in green is seen here along with calving front positions from 2015-2019. The new gate is approximately 5 km from the 2019 front.

![Kangerlussuaq_gate_old_new](https://user-images.githubusercontent.com/71708740/192774682-8f96c7ac-e90c-43e1-b592-cd58033a21c9.png)

The discharge is increased by the move:

![comparing_gates](https://user-images.githubusercontent.com/71708740/192775094-01793377-f1f0-4f5d-b374-17984754f764.png)

**Comment by mankoff** [comment]
Closed in 8c31018913ea65ca7ecb073d18365dda76c7bbef
